spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 2302
    url: jdbc:postgresql://localhost:5432/tasks_toDo_List
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create