server:
  port: 80
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${env:DATABASE_PASSWORD}
    url: ${env:DATABASE_URL}
    username: ${env:DATABASE_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update