version: '3.8'
services:
#  db:
 task-system-api:
   image: pvrosendo/task-system-api
   restart: always
   build:
     context: /../../task-system-api
     dockerfile: /../infra/image/Dockerfile
   working_dir: /task-system-api
   environment:
     TZ: America/Sao_Paulo
   ports:
     - 80:80
   command: mvn spring-boot:run
#    depends_on:
#      - db
   networks:
     - pvrosendo-network
networks:
 pvrosendo-network:
   driver: bridge

